/* AUTO-GENERATED by scripts/gen-rest-catalog.mjs — do not edit by hand.
   Source: the INSTALLED @thoughtspot/rest-api-sdk npm package (dist/index.d.ts + dist/index.js).
   To pick up new endpoints: bump the dependency, `npm install`, then `npm run gen:rest-catalog`. */
import type { ThoughtSpotRestApi } from '@thoughtspot/rest-api-sdk'

export interface RestParam {
  /** Argument name as it appears in the SDK method signature. */
  name: string
  optional: boolean
  /** A request-body object (vs. a path/query scalar). */
  isBody: boolean
  /** A file-upload arg — cannot be supplied as JSON. */
  isFile: boolean
}

export interface RestMethod {
  /** SDK method name == unique id. */
  key: string
  label: string
  group: string
  http: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH'
  path: string
  /** Ordered call arguments. */
  params: RestParam[]
  /** Curated default editor content (keyed by arg name); optional. */
  sample?: Record<string, unknown>
}

/** Every method on the aggregate ThoughtSpot REST API v2 client (160 total). */
export const REST_METHODS: RestMethod[] = [
  {
    "key": "activateUser",
    "label": "Activate User",
    "group": "Users",
    "http": "POST",
    "path": "/api/rest/2.0/users/activate",
    "params": [
      {
        "name": "activateUserRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "assignChangeAuthor",
    "label": "Assign Change Author",
    "group": "Security",
    "http": "POST",
    "path": "/api/rest/2.0/security/metadata/assign",
    "params": [
      {
        "name": "assignChangeAuthorRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "assignTag",
    "label": "Assign Tag",
    "group": "Tags",
    "http": "POST",
    "path": "/api/rest/2.0/tags/assign",
    "params": [
      {
        "name": "assignTagRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "changeUserPassword",
    "label": "Change User Password",
    "group": "Users",
    "http": "POST",
    "path": "/api/rest/2.0/users/change-password",
    "params": [
      {
        "name": "changeUserPasswordRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "commitBranch",
    "label": "Commit Branch",
    "group": "Version Control",
    "http": "POST",
    "path": "/api/rest/2.0/vcs/git/branches/commit",
    "params": [
      {
        "name": "commitBranchRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "configureAuthSettings",
    "label": "Configure Auth Settings",
    "group": "Auth & Session",
    "http": "POST",
    "path": "/api/rest/2.0/auth/configure",
    "params": [
      {
        "name": "configureAuthSettingsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "configureCommunicationChannelPreferences",
    "label": "Configure Communication Channel Preferences",
    "group": "System",
    "http": "POST",
    "path": "/api/rest/2.0/system/preferences/communication-channels/configure",
    "params": [
      {
        "name": "configureCommunicationChannelPreferencesRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "configureSecuritySettings",
    "label": "Configure Security Settings",
    "group": "System",
    "http": "POST",
    "path": "/api/rest/2.0/system/security-settings/configure",
    "params": [
      {
        "name": "configureSecuritySettingsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "connectionConfigurationSearch",
    "label": "Connection Configuration Search",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connection-configurations/search",
    "params": [
      {
        "name": "connectionConfigurationSearchRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "convertWorksheetToModel",
    "label": "Convert Worksheet To Model",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/worksheets/convert",
    "params": [
      {
        "name": "convertWorksheetToModelRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "copyObject",
    "label": "Copy Object",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/copyobject",
    "params": [
      {
        "name": "copyObjectRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createAgentConversation",
    "label": "Create Agent Conversation",
    "group": "AI",
    "http": "POST",
    "path": "/api/rest/2.0/ai/agent/conversation/create",
    "params": [
      {
        "name": "createAgentConversationRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createCalendar",
    "label": "Create Calendar",
    "group": "Custom Calendars",
    "http": "POST",
    "path": "/api/rest/2.0/calendars/create",
    "params": [
      {
        "name": "createCalendarRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createCollection",
    "label": "Create Collection",
    "group": "Collections",
    "http": "POST",
    "path": "/api/rest/2.0/collections/create",
    "params": [
      {
        "name": "createCollectionRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createConfig",
    "label": "Create Config",
    "group": "Version Control",
    "http": "POST",
    "path": "/api/rest/2.0/vcs/git/config/create",
    "params": [
      {
        "name": "createConfigRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createConnection",
    "label": "Create Connection",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connection/create",
    "params": [
      {
        "name": "createConnectionRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createConnectionConfiguration",
    "label": "Create Connection Configuration",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connection-configurations/create",
    "params": [
      {
        "name": "createConnectionConfigurationRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createConversation",
    "label": "Create Conversation",
    "group": "AI",
    "http": "POST",
    "path": "/api/rest/2.0/ai/conversation/create",
    "params": [
      {
        "name": "createConversationRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createCustomAction",
    "label": "Create Custom Action",
    "group": "Customization",
    "http": "POST",
    "path": "/api/rest/2.0/customization/custom-actions",
    "params": [
      {
        "name": "createCustomActionRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createEmailCustomization",
    "label": "Create Email Customization",
    "group": "Customization",
    "http": "POST",
    "path": "/api/rest/2.0/customization/email",
    "params": [
      {
        "name": "createEmailCustomizationRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createOrg",
    "label": "Create Org",
    "group": "Orgs",
    "http": "POST",
    "path": "/api/rest/2.0/orgs/create",
    "params": [
      {
        "name": "createOrgRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createRole",
    "label": "Create Role",
    "group": "Roles",
    "http": "POST",
    "path": "/api/rest/2.0/roles/create",
    "params": [
      {
        "name": "createRoleRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createSchedule",
    "label": "Create Schedule",
    "group": "Schedules",
    "http": "POST",
    "path": "/api/rest/2.0/schedules/create",
    "params": [
      {
        "name": "createScheduleRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createTag",
    "label": "Create Tag",
    "group": "Tags",
    "http": "POST",
    "path": "/api/rest/2.0/tags/create",
    "params": [
      {
        "name": "createTagRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createUser",
    "label": "Create User",
    "group": "Users",
    "http": "POST",
    "path": "/api/rest/2.0/users/create",
    "params": [
      {
        "name": "createUserRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createUserGroup",
    "label": "Create User Group",
    "group": "Groups",
    "http": "POST",
    "path": "/api/rest/2.0/groups/create",
    "params": [
      {
        "name": "createUserGroupRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createVariable",
    "label": "Create Variable",
    "group": "Variables",
    "http": "POST",
    "path": "/api/rest/2.0/template/variables/create",
    "params": [
      {
        "name": "createVariableRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "createWebhookConfiguration",
    "label": "Create Webhook Configuration",
    "group": "Webhooks",
    "http": "POST",
    "path": "/api/rest/2.0/webhooks/create",
    "params": [
      {
        "name": "createWebhookConfigurationRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "dbtConnection",
    "label": "Dbt Connection",
    "group": "DBT",
    "http": "POST",
    "path": "/api/rest/2.0/dbt/dbt-connection",
    "params": [
      {
        "name": "connectionName",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "databaseName",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "importType",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "accessToken",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "dbtUrl",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "accountId",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "projectId",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "dbtEnvId",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "projectName",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "fileContent",
        "optional": true,
        "isFile": true,
        "isBody": false
      }
    ]
  },
  {
    "key": "dbtGenerateSyncTml",
    "label": "Dbt Generate Sync Tml",
    "group": "DBT",
    "http": "POST",
    "path": "/api/rest/2.0/dbt/generate-sync-tml",
    "params": [
      {
        "name": "dbtConnectionIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "fileContent",
        "optional": true,
        "isFile": true,
        "isBody": false
      }
    ]
  },
  {
    "key": "dbtGenerateTml",
    "label": "Dbt Generate Tml",
    "group": "DBT",
    "http": "POST",
    "path": "/api/rest/2.0/dbt/generate-tml",
    "params": [
      {
        "name": "dbtConnectionIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "modelTables",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "importWorksheets",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "worksheets",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "fileContent",
        "optional": true,
        "isFile": true,
        "isBody": false
      }
    ]
  },
  {
    "key": "dbtSearch",
    "label": "Dbt Search",
    "group": "DBT",
    "http": "POST",
    "path": "/api/rest/2.0/dbt/search",
    "params": []
  },
  {
    "key": "deactivateUser",
    "label": "Deactivate User",
    "group": "Users",
    "http": "POST",
    "path": "/api/rest/2.0/users/deactivate",
    "params": [
      {
        "name": "deactivateUserRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "deleteCalendar",
    "label": "Delete Calendar",
    "group": "Custom Calendars",
    "http": "POST",
    "path": "/api/rest/2.0/calendars/{calendar_identifier}/delete",
    "params": [
      {
        "name": "calendarIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "deleteCollection",
    "label": "Delete Collection",
    "group": "Collections",
    "http": "POST",
    "path": "/api/rest/2.0/collections/delete",
    "params": [
      {
        "name": "deleteCollectionRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "deleteConfig",
    "label": "Delete Config",
    "group": "Version Control",
    "http": "POST",
    "path": "/api/rest/2.0/vcs/git/config/delete",
    "params": [
      {
        "name": "deleteConfigRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "deleteConnection",
    "label": "Delete Connection",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connection/delete",
    "params": [
      {
        "name": "deleteConnectionRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "deleteConnectionConfiguration",
    "label": "Delete Connection Configuration",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connection-configurations/delete",
    "params": [
      {
        "name": "deleteConnectionConfigurationRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "deleteConnectionV2",
    "label": "Delete Connection V2",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connections/{connection_identifier}/delete",
    "params": [
      {
        "name": "connectionIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "deleteCustomAction",
    "label": "Delete Custom Action",
    "group": "Customization",
    "http": "POST",
    "path": "/api/rest/2.0/customization/custom-actions/{custom_action_identifier}/delete",
    "params": [
      {
        "name": "customActionIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "deleteDbtConnection",
    "label": "Delete Dbt Connection",
    "group": "DBT",
    "http": "POST",
    "path": "/api/rest/2.0/dbt/{dbt_connection_identifier}/delete",
    "params": [
      {
        "name": "dbtConnectionIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "deleteEmailCustomization",
    "label": "Delete Email Customization",
    "group": "Customization",
    "http": "POST",
    "path": "/api/rest/2.0/customization/email/{template_identifier}/delete",
    "params": [
      {
        "name": "templateIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "deleteMetadata",
    "label": "Delete Metadata",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/delete",
    "params": [
      {
        "name": "deleteMetadataRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "deleteOrg",
    "label": "Delete Org",
    "group": "Orgs",
    "http": "POST",
    "path": "/api/rest/2.0/orgs/{org_identifier}/delete",
    "params": [
      {
        "name": "orgIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "deleteOrgEmailCustomization",
    "label": "Delete Org Email Customization",
    "group": "Customization",
    "http": "POST",
    "path": "/api/rest/2.0/customization/email/delete",
    "params": [
      {
        "name": "deleteOrgEmailCustomizationRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "deleteRole",
    "label": "Delete Role",
    "group": "Roles",
    "http": "POST",
    "path": "/api/rest/2.0/roles/{role_identifier}/delete",
    "params": [
      {
        "name": "roleIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "deleteSchedule",
    "label": "Delete Schedule",
    "group": "Schedules",
    "http": "POST",
    "path": "/api/rest/2.0/schedules/{schedule_identifier}/delete",
    "params": [
      {
        "name": "scheduleIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "deleteTag",
    "label": "Delete Tag",
    "group": "Tags",
    "http": "POST",
    "path": "/api/rest/2.0/tags/{tag_identifier}/delete",
    "params": [
      {
        "name": "tagIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "deleteUser",
    "label": "Delete User",
    "group": "Users",
    "http": "POST",
    "path": "/api/rest/2.0/users/{user_identifier}/delete",
    "params": [
      {
        "name": "userIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "deleteUserGroup",
    "label": "Delete User Group",
    "group": "Groups",
    "http": "POST",
    "path": "/api/rest/2.0/groups/{group_identifier}/delete",
    "params": [
      {
        "name": "groupIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "deleteVariable",
    "label": "Delete Variable",
    "group": "Variables",
    "http": "POST",
    "path": "/api/rest/2.0/template/variables/{identifier}/delete",
    "params": [
      {
        "name": "identifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "deleteVariables",
    "label": "Delete Variables",
    "group": "Variables",
    "http": "POST",
    "path": "/api/rest/2.0/template/variables/delete",
    "params": [
      {
        "name": "deleteVariablesRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "deleteWebhookConfigurations",
    "label": "Delete Webhook Configurations",
    "group": "Webhooks",
    "http": "POST",
    "path": "/api/rest/2.0/webhooks/delete",
    "params": [
      {
        "name": "deleteWebhookConfigurationsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "deployCommit",
    "label": "Deploy Commit",
    "group": "Version Control",
    "http": "POST",
    "path": "/api/rest/2.0/vcs/git/commits/deploy",
    "params": [
      {
        "name": "deployCommitRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "downloadConnectionMetadataChanges",
    "label": "Download Connection Metadata Changes",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connections/download-connection-metadata-changes/{connection_identifier}",
    "params": [
      {
        "name": "connectionIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "exportAnswerReport",
    "label": "Export Answer Report",
    "group": "Reports",
    "http": "POST",
    "path": "/api/rest/2.0/report/answer",
    "params": [
      {
        "name": "exportAnswerReportRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "exportLiveboardReport",
    "label": "Export Liveboard Report",
    "group": "Reports",
    "http": "POST",
    "path": "/api/rest/2.0/report/liveboard",
    "params": [
      {
        "name": "exportLiveboardReportRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "exportMetadataTML",
    "label": "Export Metadata TML",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/tml/export",
    "params": [
      {
        "name": "exportMetadataTMLRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "exportMetadataTMLBatched",
    "label": "Export Metadata TML Batched",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/tml/export/batch",
    "params": [
      {
        "name": "exportMetadataTMLBatchedRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "fetchAnswerData",
    "label": "Fetch Answer Data",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/answer/data",
    "params": [
      {
        "name": "fetchAnswerDataRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "fetchAnswerSqlQuery",
    "label": "Fetch Answer Sql Query",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/answer/sql",
    "params": [
      {
        "name": "fetchAnswerSqlQueryRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "fetchAsyncImportTaskStatus",
    "label": "Fetch Async Import Task Status",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/tml/async/status",
    "params": [
      {
        "name": "fetchAsyncImportTaskStatusRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "fetchColumnSecurityRules",
    "label": "Fetch Column Security Rules",
    "group": "Security",
    "http": "POST",
    "path": "/api/rest/2.0/security/column/rules/fetch",
    "params": [
      {
        "name": "fetchColumnSecurityRulesRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "fetchConnectionDiffStatus",
    "label": "Fetch Connection Diff Status",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connections/fetch-connection-diff-status/{connection_identifier}",
    "params": [
      {
        "name": "connectionIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "fetchLiveboardData",
    "label": "Fetch Liveboard Data",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/liveboard/data",
    "params": [
      {
        "name": "fetchLiveboardDataRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "fetchLiveboardSqlQuery",
    "label": "Fetch Liveboard Sql Query",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/liveboard/sql",
    "params": [
      {
        "name": "fetchLiveboardSqlQueryRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "fetchLogs",
    "label": "Fetch Logs",
    "group": "Logs",
    "http": "POST",
    "path": "/api/rest/2.0/logs/fetch",
    "params": [
      {
        "name": "fetchLogsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "fetchObjectPrivileges",
    "label": "Fetch Object Privileges",
    "group": "Security",
    "http": "POST",
    "path": "/api/rest/2.0/security/metadata/fetch-object-privileges",
    "params": [
      {
        "name": "fetchObjectPrivilegesRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "fetchPermissionsOfPrincipals",
    "label": "Fetch Permissions Of Principals",
    "group": "Security",
    "http": "POST",
    "path": "/api/rest/2.0/security/principals/fetch-permissions",
    "params": [
      {
        "name": "fetchPermissionsOfPrincipalsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "fetchPermissionsOnMetadata",
    "label": "Fetch Permissions On Metadata",
    "group": "Security",
    "http": "POST",
    "path": "/api/rest/2.0/security/metadata/fetch-permissions",
    "params": [
      {
        "name": "fetchPermissionsOnMetadataRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "forceLogoutUsers",
    "label": "Force Logout Users",
    "group": "Users",
    "http": "POST",
    "path": "/api/rest/2.0/users/force-logout",
    "params": [
      {
        "name": "forceLogoutUsersRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "generateCSV",
    "label": "Generate CSV",
    "group": "Custom Calendars",
    "http": "POST",
    "path": "/api/rest/2.0/calendars/generate-csv",
    "params": [
      {
        "name": "generateCSVRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "getCurrentUserInfo",
    "label": "Get Current User Info",
    "group": "Auth & Session",
    "http": "GET",
    "path": "/api/rest/2.0/auth/session/user",
    "params": []
  },
  {
    "key": "getCurrentUserToken",
    "label": "Get Current User Token",
    "group": "Auth & Session",
    "http": "GET",
    "path": "/api/rest/2.0/auth/session/token",
    "params": []
  },
  {
    "key": "getCustomAccessToken",
    "label": "Get Custom Access Token",
    "group": "Auth & Session",
    "http": "POST",
    "path": "/api/rest/2.0/auth/token/custom",
    "params": [
      {
        "name": "getCustomAccessTokenRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "getDataSourceSuggestions",
    "label": "Get Data Source Suggestions",
    "group": "AI",
    "http": "POST",
    "path": "/api/rest/2.0/ai/data-source-suggestions",
    "params": [
      {
        "name": "getDataSourceSuggestionsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "getFullAccessToken",
    "label": "Get Full Access Token",
    "group": "Auth & Session",
    "http": "POST",
    "path": "/api/rest/2.0/auth/token/full",
    "params": [
      {
        "name": "getFullAccessTokenRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "getNLInstructions",
    "label": "Get NL Instructions",
    "group": "AI",
    "http": "POST",
    "path": "/api/rest/2.0/ai/instructions/get",
    "params": [
      {
        "name": "getNLInstructionsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "getObjectAccessToken",
    "label": "Get Object Access Token",
    "group": "Auth & Session",
    "http": "POST",
    "path": "/api/rest/2.0/auth/token/object",
    "params": [
      {
        "name": "getObjectAccessTokenRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "getRelevantQuestions",
    "label": "Get Relevant Questions",
    "group": "AI",
    "http": "POST",
    "path": "/api/rest/2.0/ai/relevant-questions/",
    "params": [
      {
        "name": "getRelevantQuestionsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "getSystemConfig",
    "label": "Get System Config",
    "group": "System",
    "http": "GET",
    "path": "/api/rest/2.0/system/config",
    "params": []
  },
  {
    "key": "getSystemInformation",
    "label": "Get System Information",
    "group": "System",
    "http": "GET",
    "path": "/api/rest/2.0/system",
    "params": []
  },
  {
    "key": "getSystemOverrideInfo",
    "label": "Get System Override Info",
    "group": "System",
    "http": "GET",
    "path": "/api/rest/2.0/system/config-overrides",
    "params": []
  },
  {
    "key": "importMetadataTML",
    "label": "Import Metadata TML",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/tml/import",
    "params": [
      {
        "name": "importMetadataTMLRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "importMetadataTMLAsync",
    "label": "Import Metadata TML Async",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/tml/async/import",
    "params": [
      {
        "name": "importMetadataTMLAsyncRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "importUserGroups",
    "label": "Import User Groups",
    "group": "Groups",
    "http": "POST",
    "path": "/api/rest/2.0/groups/import",
    "params": [
      {
        "name": "importUserGroupsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "importUsers",
    "label": "Import Users",
    "group": "Users",
    "http": "POST",
    "path": "/api/rest/2.0/users/import",
    "params": [
      {
        "name": "importUsersRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "login",
    "label": "Login",
    "group": "Auth & Session",
    "http": "POST",
    "path": "/api/rest/2.0/auth/session/login",
    "params": [
      {
        "name": "loginRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "logout",
    "label": "Logout",
    "group": "Auth & Session",
    "http": "POST",
    "path": "/api/rest/2.0/auth/session/logout",
    "params": []
  },
  {
    "key": "manageObjectPrivilege",
    "label": "Manage Object Privilege",
    "group": "Security",
    "http": "POST",
    "path": "/api/rest/2.0/security/metadata/manage-object-privilege",
    "params": [
      {
        "name": "manageObjectPrivilegeRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "parameterizeMetadata",
    "label": "Parameterize Metadata",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/parameterize",
    "params": [
      {
        "name": "parameterizeMetadataRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "parameterizeMetadataFields",
    "label": "Parameterize Metadata Fields",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/parameterize-fields",
    "params": [
      {
        "name": "parameterizeMetadataFieldsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "publishMetadata",
    "label": "Publish Metadata",
    "group": "Security",
    "http": "POST",
    "path": "/api/rest/2.0/security/metadata/publish",
    "params": [
      {
        "name": "publishMetadataRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "putVariableValues",
    "label": "Put Variable Values",
    "group": "Variables",
    "http": "POST",
    "path": "/api/rest/2.0/template/variables/{identifier}/update-values",
    "params": [
      {
        "name": "identifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "putVariableValuesRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "queryGetDecomposedQuery",
    "label": "Query Get Decomposed Query",
    "group": "AI",
    "http": "POST",
    "path": "/api/rest/2.0/ai/analytical-questions",
    "params": [
      {
        "name": "queryGetDecomposedQueryRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "resetUserPassword",
    "label": "Reset User Password",
    "group": "Users",
    "http": "POST",
    "path": "/api/rest/2.0/users/reset-password",
    "params": [
      {
        "name": "resetUserPasswordRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "revertCommit",
    "label": "Revert Commit",
    "group": "Version Control",
    "http": "POST",
    "path": "/api/rest/2.0/vcs/git/commits/{commit_id}/revert",
    "params": [
      {
        "name": "commitId",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "revertCommitRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "revokeRefreshTokens",
    "label": "Revoke Refresh Tokens",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connections/{connection_identifier}/revoke-refresh-tokens",
    "params": [
      {
        "name": "connectionIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "revokeRefreshTokensRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "revokeToken",
    "label": "Revoke Token",
    "group": "Auth & Session",
    "http": "POST",
    "path": "/api/rest/2.0/auth/token/revoke",
    "params": [
      {
        "name": "revokeTokenRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchAuthSettings",
    "label": "Search Auth Settings",
    "group": "Auth & Session",
    "http": "POST",
    "path": "/api/rest/2.0/auth/search",
    "params": [
      {
        "name": "searchAuthSettingsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchCalendars",
    "label": "Search Calendars",
    "group": "Custom Calendars",
    "http": "POST",
    "path": "/api/rest/2.0/calendars/search",
    "params": [
      {
        "name": "searchCalendarsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchChannelHistory",
    "label": "Search Channel History",
    "group": "Jobs",
    "http": "POST",
    "path": "/api/rest/2.0/jobs/history/communication-channels/search",
    "params": [
      {
        "name": "searchChannelHistoryRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchCollections",
    "label": "Search Collections",
    "group": "Collections",
    "http": "POST",
    "path": "/api/rest/2.0/collections/search",
    "params": [
      {
        "name": "searchCollectionsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchCommits",
    "label": "Search Commits",
    "group": "Version Control",
    "http": "POST",
    "path": "/api/rest/2.0/vcs/git/commits/search",
    "params": [
      {
        "name": "searchCommitsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchCommunicationChannelPreferences",
    "label": "Search Communication Channel Preferences",
    "group": "System",
    "http": "POST",
    "path": "/api/rest/2.0/system/preferences/communication-channels/search",
    "params": [
      {
        "name": "searchCommunicationChannelPreferencesRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchConfig",
    "label": "Search Config",
    "group": "Version Control",
    "http": "POST",
    "path": "/api/rest/2.0/vcs/git/config/search",
    "params": [
      {
        "name": "searchConfigRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchConnection",
    "label": "Search Connection",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connection/search",
    "params": [
      {
        "name": "searchConnectionRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ],
    "sample": {
      "searchConnectionRequest": {
        "record_size": 10
      }
    }
  },
  {
    "key": "searchCustomActions",
    "label": "Search Custom Actions",
    "group": "Customization",
    "http": "POST",
    "path": "/api/rest/2.0/customization/custom-actions/search",
    "params": [
      {
        "name": "searchCustomActionsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchData",
    "label": "Search Data",
    "group": "Data",
    "http": "POST",
    "path": "/api/rest/2.0/searchdata",
    "params": [
      {
        "name": "searchDataRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchEmailCustomization",
    "label": "Search Email Customization",
    "group": "Customization",
    "http": "POST",
    "path": "/api/rest/2.0/customization/email/search",
    "params": [
      {
        "name": "searchEmailCustomizationRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchMetadata",
    "label": "Search Metadata",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/search",
    "params": [
      {
        "name": "searchMetadataRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ],
    "sample": {
      "searchMetadataRequest": {
        "metadata": [
          {
            "type": "LIVEBOARD"
          }
        ],
        "record_size": 10
      }
    }
  },
  {
    "key": "searchOrgs",
    "label": "Search Orgs",
    "group": "Orgs",
    "http": "POST",
    "path": "/api/rest/2.0/orgs/search",
    "params": [
      {
        "name": "searchOrgsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchRoles",
    "label": "Search Roles",
    "group": "Roles",
    "http": "POST",
    "path": "/api/rest/2.0/roles/search",
    "params": [
      {
        "name": "searchRolesRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchSchedules",
    "label": "Search Schedules",
    "group": "Schedules",
    "http": "POST",
    "path": "/api/rest/2.0/schedules/search",
    "params": [
      {
        "name": "searchSchedulesRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ],
    "sample": {
      "searchSchedulesRequest": {
        "record_size": 10
      }
    }
  },
  {
    "key": "searchSecuritySettings",
    "label": "Search Security Settings",
    "group": "System",
    "http": "POST",
    "path": "/api/rest/2.0/system/security-settings/search",
    "params": [
      {
        "name": "searchSecuritySettingsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchTags",
    "label": "Search Tags",
    "group": "Tags",
    "http": "POST",
    "path": "/api/rest/2.0/tags/search",
    "params": [
      {
        "name": "searchTagsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchUserGroups",
    "label": "Search User Groups",
    "group": "Groups",
    "http": "POST",
    "path": "/api/rest/2.0/groups/search",
    "params": [
      {
        "name": "searchUserGroupsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ],
    "sample": {
      "searchUserGroupsRequest": {
        "record_size": 10
      }
    }
  },
  {
    "key": "searchUsers",
    "label": "Search Users",
    "group": "Users",
    "http": "POST",
    "path": "/api/rest/2.0/users/search",
    "params": [
      {
        "name": "searchUsersRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ],
    "sample": {
      "searchUsersRequest": {
        "record_size": 10
      }
    }
  },
  {
    "key": "searchVariables",
    "label": "Search Variables",
    "group": "Variables",
    "http": "POST",
    "path": "/api/rest/2.0/template/variables/search",
    "params": [
      {
        "name": "searchVariablesRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "searchWebhookConfigurations",
    "label": "Search Webhook Configurations",
    "group": "Webhooks",
    "http": "POST",
    "path": "/api/rest/2.0/webhooks/search",
    "params": [
      {
        "name": "searchWebhookConfigurationsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "sendAgentConversationMessage",
    "label": "Send Agent Conversation Message",
    "group": "AI",
    "http": "POST",
    "path": "/api/rest/2.0/ai/agent/conversation/{conversation_identifier}/send",
    "params": [
      {
        "name": "conversationIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "sendAgentConversationMessageRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "sendAgentConversationMessageStreaming",
    "label": "Send Agent Conversation Message Streaming",
    "group": "AI",
    "http": "POST",
    "path": "/api/rest/2.0/ai/agent/conversation/{conversation_identifier}/send/stream",
    "params": [
      {
        "name": "conversationIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "sendAgentConversationMessageStreamingRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "sendAgentMessage",
    "label": "Send Agent Message",
    "group": "AI",
    "http": "POST",
    "path": "/api/rest/2.0/ai/agent/{conversation_identifier}/converse",
    "params": [
      {
        "name": "conversationIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "sendAgentMessageRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "sendAgentMessageStreaming",
    "label": "Send Agent Message Streaming",
    "group": "AI",
    "http": "POST",
    "path": "/api/rest/2.0/ai/agent/converse/sse",
    "params": [
      {
        "name": "sendAgentMessageStreamingRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "sendMessage",
    "label": "Send Message",
    "group": "AI",
    "http": "POST",
    "path": "/api/rest/2.0/ai/conversation/{conversation_identifier}/converse",
    "params": [
      {
        "name": "conversationIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "sendMessageRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "setNLInstructions",
    "label": "Set NL Instructions",
    "group": "AI",
    "http": "POST",
    "path": "/api/rest/2.0/ai/instructions/set",
    "params": [
      {
        "name": "setNLInstructionsRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "shareMetadata",
    "label": "Share Metadata",
    "group": "Security",
    "http": "POST",
    "path": "/api/rest/2.0/security/metadata/share",
    "params": [
      {
        "name": "shareMetadataRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "singleAnswer",
    "label": "Single Answer",
    "group": "AI",
    "http": "POST",
    "path": "/api/rest/2.0/ai/answer/create",
    "params": [
      {
        "name": "singleAnswerRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "stopConversation",
    "label": "Stop Conversation",
    "group": "AI",
    "http": "POST",
    "path": "/api/rest/2.0/ai/agent/conversation/{conversation_identifier}/stop-response",
    "params": [
      {
        "name": "conversationIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      }
    ]
  },
  {
    "key": "syncMetadata",
    "label": "Sync Metadata",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connections/{connection_identifier}/resync-metadata",
    "params": [
      {
        "name": "connectionIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "syncMetadataRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "unassignTag",
    "label": "Unassign Tag",
    "group": "Tags",
    "http": "POST",
    "path": "/api/rest/2.0/tags/unassign",
    "params": [
      {
        "name": "unassignTagRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "unparameterizeMetadata",
    "label": "Unparameterize Metadata",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/unparameterize",
    "params": [
      {
        "name": "unparameterizeMetadataRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "unpublishMetadata",
    "label": "Unpublish Metadata",
    "group": "Security",
    "http": "POST",
    "path": "/api/rest/2.0/security/metadata/unpublish",
    "params": [
      {
        "name": "unpublishMetadataRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateCalendar",
    "label": "Update Calendar",
    "group": "Custom Calendars",
    "http": "POST",
    "path": "/api/rest/2.0/calendars/{calendar_identifier}/update",
    "params": [
      {
        "name": "calendarIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "updateCalendarRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateCollection",
    "label": "Update Collection",
    "group": "Collections",
    "http": "POST",
    "path": "/api/rest/2.0/collections/{collection_identifier}/update",
    "params": [
      {
        "name": "collectionIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "updateCollectionRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateColumnSecurityRules",
    "label": "Update Column Security Rules",
    "group": "Security",
    "http": "POST",
    "path": "/api/rest/2.0/security/column/rules/update",
    "params": [
      {
        "name": "updateColumnSecurityRulesRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateConfig",
    "label": "Update Config",
    "group": "Version Control",
    "http": "POST",
    "path": "/api/rest/2.0/vcs/git/config/update",
    "params": [
      {
        "name": "updateConfigRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateConnection",
    "label": "Update Connection",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connection/update",
    "params": [
      {
        "name": "updateConnectionRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateConnectionConfiguration",
    "label": "Update Connection Configuration",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connection-configurations/{configuration_identifier}/update",
    "params": [
      {
        "name": "configurationIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "updateConnectionConfigurationRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateConnectionStatus",
    "label": "Update Connection Status",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connections/{connection_identifier}/status",
    "params": [
      {
        "name": "connectionIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "updateConnectionStatusRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateConnectionV2",
    "label": "Update Connection V2",
    "group": "Connections",
    "http": "POST",
    "path": "/api/rest/2.0/connections/{connection_identifier}/update",
    "params": [
      {
        "name": "connectionIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "updateConnectionV2Request",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateCustomAction",
    "label": "Update Custom Action",
    "group": "Customization",
    "http": "POST",
    "path": "/api/rest/2.0/customization/custom-actions/{custom_action_identifier}/update",
    "params": [
      {
        "name": "customActionIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "updateCustomActionRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateDbtConnection",
    "label": "Update Dbt Connection",
    "group": "DBT",
    "http": "POST",
    "path": "/api/rest/2.0/dbt/update-dbt-connection",
    "params": [
      {
        "name": "dbtConnectionIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "connectionName",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "databaseName",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "importType",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "accessToken",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "dbtUrl",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "accountId",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "projectId",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "dbtEnvId",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "projectName",
        "optional": true,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "fileContent",
        "optional": true,
        "isFile": true,
        "isBody": false
      }
    ]
  },
  {
    "key": "updateEmailCustomization",
    "label": "Update Email Customization",
    "group": "Customization",
    "http": "POST",
    "path": "/api/rest/2.0/customization/email/update",
    "params": [
      {
        "name": "updateEmailCustomizationRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateMetadataHeader",
    "label": "Update Metadata Header",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/headers/update",
    "params": [
      {
        "name": "updateMetadataHeaderRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateMetadataObjId",
    "label": "Update Metadata Obj Id",
    "group": "Metadata",
    "http": "POST",
    "path": "/api/rest/2.0/metadata/update-obj-id",
    "params": [
      {
        "name": "updateMetadataObjIdRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateOrg",
    "label": "Update Org",
    "group": "Orgs",
    "http": "POST",
    "path": "/api/rest/2.0/orgs/{org_identifier}/update",
    "params": [
      {
        "name": "orgIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "updateOrgRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateRole",
    "label": "Update Role",
    "group": "Roles",
    "http": "POST",
    "path": "/api/rest/2.0/roles/{role_identifier}/update",
    "params": [
      {
        "name": "roleIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "updateRoleRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateSchedule",
    "label": "Update Schedule",
    "group": "Schedules",
    "http": "POST",
    "path": "/api/rest/2.0/schedules/{schedule_identifier}/update",
    "params": [
      {
        "name": "scheduleIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "updateScheduleRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateSystemConfig",
    "label": "Update System Config",
    "group": "System",
    "http": "POST",
    "path": "/api/rest/2.0/system/config-update",
    "params": [
      {
        "name": "updateSystemConfigRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateTag",
    "label": "Update Tag",
    "group": "Tags",
    "http": "POST",
    "path": "/api/rest/2.0/tags/{tag_identifier}/update",
    "params": [
      {
        "name": "tagIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "updateTagRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateUser",
    "label": "Update User",
    "group": "Users",
    "http": "POST",
    "path": "/api/rest/2.0/users/{user_identifier}/update",
    "params": [
      {
        "name": "userIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "updateUserRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateUserGroup",
    "label": "Update User Group",
    "group": "Groups",
    "http": "POST",
    "path": "/api/rest/2.0/groups/{group_identifier}/update",
    "params": [
      {
        "name": "groupIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "updateUserGroupRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateVariable",
    "label": "Update Variable",
    "group": "Variables",
    "http": "POST",
    "path": "/api/rest/2.0/template/variables/{identifier}/update",
    "params": [
      {
        "name": "identifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "updateVariableRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateVariableValues",
    "label": "Update Variable Values",
    "group": "Variables",
    "http": "POST",
    "path": "/api/rest/2.0/template/variables/update-values",
    "params": [
      {
        "name": "updateVariableValuesRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "updateWebhookConfiguration",
    "label": "Update Webhook Configuration",
    "group": "Webhooks",
    "http": "POST",
    "path": "/api/rest/2.0/webhooks/{webhook_identifier}/update",
    "params": [
      {
        "name": "webhookIdentifier",
        "optional": false,
        "isFile": false,
        "isBody": false
      },
      {
        "name": "updateWebhookConfigurationRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "validateCommunicationChannel",
    "label": "Validate Communication Channel",
    "group": "System",
    "http": "POST",
    "path": "/api/rest/2.0/system/communication-channels/validate",
    "params": [
      {
        "name": "validateCommunicationChannelRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "validateEmailCustomization",
    "label": "Validate Email Customization",
    "group": "Customization",
    "http": "POST",
    "path": "/api/rest/2.0/customization/email/validate",
    "params": []
  },
  {
    "key": "validateMerge",
    "label": "Validate Merge",
    "group": "Version Control",
    "http": "POST",
    "path": "/api/rest/2.0/vcs/git/branches/validate",
    "params": [
      {
        "name": "validateMergeRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  },
  {
    "key": "validateToken",
    "label": "Validate Token",
    "group": "Auth & Session",
    "http": "POST",
    "path": "/api/rest/2.0/auth/token/validate",
    "params": [
      {
        "name": "validateTokenRequest",
        "optional": false,
        "isFile": false,
        "isBody": true
      }
    ]
  }
]

export const REST_GROUP_ORDER = ["Auth & Session","Metadata","Data","Users","Groups","Roles","Orgs","Tags","Collections","Connections","Schedules","AI","Security","System","Customization","Webhooks","Reports","Jobs","Variables","Version Control","DBT","Custom Calendars","Logs","Other"]

const REST_GROUP_COLOR: Record<string, string> = {
  'Auth & Session': '#3B82F6', Metadata: '#06B6D4', Data: '#0EA5E9', Users: '#8B5CF6',
  Groups: '#A855F7', Roles: '#9333EA', Orgs: '#D946EF', Tags: '#F59E0B',
  Collections: '#EAB308', Connections: '#F97316', Schedules: '#EC4899', AI: '#14B8A6',
  Security: '#EF4444', System: '#64748B', Customization: '#10B981', Webhooks: '#06B6D4',
  Reports: '#0891B2', Jobs: '#0D9488', Variables: '#7C5CFC', 'Version Control': '#2563EB',
  DBT: '#65A30D', 'Custom Calendars': '#DB2777', Logs: '#94A3B8', Other: '#64748B',
}

export function restGroupColor(group: string): string {
  return REST_GROUP_COLOR[group] ?? '#64748B'
}

export function findRestMethod(key: string): RestMethod | undefined {
  return REST_METHODS.find((m) => m.key === key)
}

/** Build the default editor object for a method: one key per non-file arg. */
export function defaultBodyFor(m: RestMethod): Record<string, unknown> {
  if (m.sample) return m.sample
  const obj: Record<string, unknown> = {}
  for (const p of m.params) {
    if (p.isFile) continue
    obj[p.name] = p.isBody ? {} : ''
  }
  return obj
}

/** True when the method takes no JSON-supplied arguments. */
export function takesNoArgs(m: RestMethod): boolean {
  return m.params.every((p) => p.isFile)
}

/** Build the positional argument list from the parsed editor object. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function buildArgs(m: RestMethod, body: any): unknown[] {
  return m.params.map((p) => (p.isFile ? undefined : body?.[p.name]))
}

/** Invoke the method by name with positional args derived from `body`. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function invokeRest(api: ThoughtSpotRestApi, m: RestMethod, body: any): Promise<unknown> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const fn = (api as any)[m.key] as (...a: unknown[]) => Promise<unknown>
  return fn.apply(api, buildArgs(m, body))
}
